---
site_name: TS-2025 From Good to Great - Enhancing Customer Experience with the Webex Contact Center Flow Designer
site_description: TS-2025 From Good to Great - Enhancing Customer Experience with the Webex Contact Center Flow Designer
site_author: Dimitri Bokatov, Yaroslav Bondar
site_name: Tech Summit Labs
# must be same as "site_name"
copyright: Copyright &copy; 2025 Cisco Systems Inc. All Rights Reserved.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
    - content.tooltips
    - content.footnote.tooltips
    - codehilite
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom      
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/copy-button.js
  - js/attendee-id.js
plugins:
  - search
  #- with-pdf:
  #    cover_title: TS-2025
  #    cover_subtitle: "From Good to Great: Enhancing Customer Experience with the Webex Contact Center Flow Designer"
  #    cover_logo: template_assets/Cisco-Live-White-Blue-APJC.svg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top   
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - Getting Started:
      - Lab Overview: ./main/overview.md
      - Getting to know your environment: ./main/PreRequisites.md
###      - Chrome and Webex App Setup: ./main/Browser_and_Desktop_Setup.md 
      - Choose Your Adventure: ./main/Choose_Your_Adventure.md
      ## - Flow Designer Overview [To be moved to presentation]: ./main/FlowDesignerOverview.md
  - CORE TRACK:
      - Lab Guide:
            - "Mission 1: Basic Call Routing (Flow Template, TTS, Language)": ./main/CoreTrack_Mission1.md
            - "Mission 2: Skill-Based Routing": ./main/CoreTrack_Mission2.md
            - "Mission 3: Using Business Hours": ./main/CoreTrack_Mission3.md
            - "Mission 4: Work with Event Flow": ./main/CoreTrack_Mission4.md
            - "Mission 5: Post Call Survey": ./main/CoreTrack_Mission5.md
            - "Mission 6: Subflow and Variable Override": ./main/CoreTrack_Mission6.md
            - "Mission 7: Using Flow Designer Tools": ./main/CoreTrack_Mission7.md
      - Conclusion: ./main/CoreTrack_Conclusion.md
  - API TRACK:
      - Lab Guide:
            - "Introduction to Developer Portal": ./main/APITrack_DeveloperPortal.md
            - "Mission 1: Emergency config change": ./main/APITrack_Mission1.md
            - "Mission 2: Routing facilitation": ./main/APITrack_Mission2.md 
            - "Mission 3: Last Agent Routing": ./main/APITrack_Mission3.md
            - "Mission 4: Routing Returning Callers": ./main/APITrack_Mission4.md
            - "Mission 5: Personalized Customer Notification with Functions": ./main/APITrack_Mission5.md
      - Conclusion: ./main/APITrack_Conclusion.md
  - CALLBACK TRACK:
      - Lab Guide:
            - "Mission 1: Basic Call Routing (Flow Template, TTS, Language)": ./main/CallbackTrack_Mission1.md ## Same as CoreTrack Mission1
            - "Mission 2: Adding Callback Functionality": ./main/CallbackTrack_Mission2.md ## Same as CoreTrack Mission3
            - "Mission 3: CallBack on Global Error": ./main/CallbackTrack_Mission3.md
            - "Mission 4: Preventing Callback Duplication": ./main/CallbackTrack_Mission4.md
            - "Mission 5: Adding Scheduled IVR Callback": ./main/CallbackTrack_Mission5.md
            - "Mission 6: Adding Personalized Callback": ./main/CallbackTrack_Mission6.md  
      - Conclusion: ./main/CallbackTrack_Conclusion.md
  - AI AGENT TRACK:
      - Autonomous AI Agent:
            - "Lab overview": ./main/AI_Lab_Aut_Overview.md
            - "Mission 1: Create AI Autonomous Agent": ./main/AI_Lab_Aut_Mission1.md
            - "Mission 2: Integrating the AI Agent with Flow for Voice Calls": ./main/AI_Lab_Aut_Mission2.md
            - "Mission 3: Send Custom data to Autonomous AI Agent": ./main/AI_Lab_Aut_Mission3_CustomData.md
            - "Mission 4: Configure Fulfilment Action to create an order": ./main/AI_Lab_Aut_Mission4.md
            - "Mission 5: Configure Transfer Action for a Specific Queue": ./main/AI_Lab_Aut_Mission5_Transfer.md
            - "Mission 6: Configure Transfer Action for Webex AI Agent": ./main/AI_Lab_Aut_Mission6_Transfer2.md
            - "(Optional) Mission 7: Configure Action with MCP": ./main/AI_Lab_Aut_Mission7_MCP.md
            - "(Optional) Mission 8: Configure Action with A2A": ./main/AI_Lab_Aut_Mission8_A2A.md
            - "Mission 9: Customize AI Agent Language": ./main/AI_Lab_Aut_Mission9_Language.md
      - Scripted AI Agent [BONUS]:
            - "Lab overview": ./main/AI_Lab_Scripted_Overview.md
            - "Mission 1: Configure Scripted Agent to answer basic questions": ./main/AI_Lab_Scripted_Mission1.md
            - "Mission 2 : Integrate Scripted Agent with Voice Flow.": ./main/AI_Lab_Scripted_Mission3.md
            - "Mission 3 : Configure flow to track an order": ./main/AI_Lab_Scripted_Mission4.md
            - "Mission 4 : Configure the fulfillment": ./main/AI_Lab_Scripted_Mission5.md
            - "Mission 5 : Deliver fulfillment results to the caller": ./main/AI_Lab_Scripted_Mission6.md
      - Conclusion: ./main/AI_Lab_Agent_Conclusion.md
  - AI ASSISTANT:
      - AI Assistant Features:  
            - "Lab overview": ./main/AI_Lab_Features_Overview.md
            - "Mission 1: Real Time Transcript": ./main/AI_Lab_Assist_RT_Transcript.md
            - "Mission 2: Wrap Up Summary": ./main/AI_Lab_Assist_WrapUp_Summary.md
            - "Mission 3: Call Drop Summary": ./main/AI_Lab_Assist_CallDrop_Summary.md
            - "Mission 4: Agent Welbeing": ./main/AI_Lab_Assist_Agent_Welbeing.md
            - "Mission 5: AI Agent Transfer Summary": ./main/AI_Lab_Assist_AI_Agent_Transfer_Summary.md
            - "(Read Only) Mission 5: AutoCSAT": ./main/AI_Lab_Assist_AutoCSAT.md

      - Real-Time Assist (Suggested Responses):
            - "Lab overview": ./main/AI_Lab_Suggested_Responses_Overview.md
            - "Mission 1": ./main/AI_Lab_Suggested_Responseds_Mission1.md
            - "(Optional) Mission2 ": ./main/AI_Lab_Suggested_Responseds_Mission2.md
      - Topic Analytics:
            - "Lab overview": ./main/AI_Lab_Topic_Overview.md
            - "Mission 1: Explore Topic Analytics": ./main/AI_Lab_Topic_Mission1.md
            - "(Read Only) Mission 2: Explore Real-Time Topic Analytics": ./main/AI_Lab_Real_Time_Topic_Mission1.md 
      - Conclusion: ./main/AI_Lab_Assistant_Conclusion.md
  - FINAL CHALLENGE:
      - Troubleshooting Mission:
            - "Final Challenge: Production flow is failing!": ./main/FinalBossFight_Mission.md
###            - "Hint for Final Challenge Mission!": ./main/FinalBossFight_Hint1.md
###            - "Solution Guidance for Final Challenge Fight Mission!": ./main/FinalBossFight_Solution.md
  - Quick Links: quicklinks.md
###  - Ask a Question<i class="fa-solid fa-hand" style="color:#63E6BE;"></i>: slido-QA-iFrame.md

